---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  project: default
  sources:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 5.51.6
      helm:
        releaseName: argo-cd
        valueFiles:
          - $values/infrastructure/base/argo-cd-values.yaml
    - ref: values
      repoURL: https://github.com/gadgetmg/argo-test
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-cd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
